name: 'Stale issue handler'

on:
  workflow_dispatch:
  schedule:
    # Runs every day at 23:40 UTC
    - cron: '40 23 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'yellinzero'
    steps:
      - uses: actions/stale@v10
        name: 'Mark and close stale issues'
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          ascending: true
          days-before-issue-close: 7
          days-before-issue-stale: 30
          days-before-pr-stale: -1
          days-before-pr-close: -1
          remove-issue-stale-when-updated: true
          stale-issue-label: 'stale'
          exempt-issue-labels: 'pinned,roadmap,help wanted'
          stale-issue-message: "This issue has been automatically marked as stale due to 30 days of inactivity. It will be closed in 7 days unless there's further activity."
          close-issue-message: 'This issue has been automatically closed due to inactivity. Feel free to reopen if still relevant.'
          operations-per-run: 100
